//export defaults here so that tere is less lines of code when importing pages into router in App.tsx
export { default as HomeLayout } from './HomeLayout'
export { default as Dashboard } from './Dashboard'
export { default as DashboardLayout } from './DashboardLayout'
export { default as FAQ } from './FAQ'
export { default as ErrorPage } from './ErrorPage'
export { default as Login } from './Login'
export { default as AddJob } from './AddJob'
export { default as Admin } from './Admin'
export { default as DeleteJob } from './DeleteJob'
export { default as Register } from './Register'
export { default as Stats } from './Stats'
export { default as Profile } from './Profile'
export { default as AllJobs } from './AllJobs'
